// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"OrangeCustomEvents","status":true,"description":"This plugin Will let you add or copy events to the current map","parameters":{}},
{"name":"OrangeCustomEventCreator","status":true,"description":"This plugin Will let you create virtual events with script calls","parameters":{}},
{"name":"MMO_Core","status":false,"description":"MMORPG Maker MV - Core","parameters":{"Server Location":"http://beta.guaranpis.es:8097/"}},
{"name":"MMO_Core_Player","status":false,"description":"MMORPG Maker MV - Core Handling Player","parameters":{"Mouse Movements":"true","Use Native Respawn":"false"}},
{"name":"MMO_Core_Players","status":false,"description":"MMORPG Maker MV - Core Handling Players","parameters":{}},
{"name":"MMO_Core_Party","status":false,"description":"MMORPG Maker MV - Core Handling Parties","parameters":{}},
{"name":"MMO_Core_Party_Combat","status":false,"description":"MMORPG Maker MV - Core Handling Combat in Party","parameters":{}},
{"name":"MMO_Core_Bank","status":false,"description":"MMORPG Maker MV - Core Handling Bank","parameters":{}},
{"name":"MMO_ChatBox","status":false,"description":"MMORPG Maker MV - ChatBox","parameters":{"chatPosition":"TOP LEFT"}},
{"name":"MMO_LoginForm","status":false,"description":"MMORPG Maker MV - Login Form","parameters":{"allowAccountCreation":"Yes"}},
{"name":"MMO_Overhead","status":false,"description":"Add name over actors name","parameters":{}},
{"name":"SRD_UltraBase","status":false,"description":"Contains code required for HUD Maker Ultra. Does not affect the RPG Maker codebase.","parameters":{}},
{"name":"SRD_HUDMakerUltra","status":false,"description":"Allows you to create and use HUDs for the map and battles.\r\nRequires the HUD Maker Ultra editor.","parameters":{"Auto-Reload HUD Data":"false","Enable Screenshots":"false","Hide Battle Status Window":"false","Hide Battle Selection Window":"false","Fade During Events":"true","Event Fade Opacity":"125","Fade Duration":"10","Map Visibility Code":"return true;","Battle Visibility Code":"return true;"}},
{"name":"Guaranpis","status":true,"description":"Plugin exclusivo para Guaranpis.","parameters":{}}
];
